### PASO 1 — CARGA DE DATASETS DE OBRA

In [1]:
# ===============================
# CARGA DATASETS OBRA
# ===============================

from pathlib import Path
import pandas as pd
import numpy as np

BASE = Path(r"C:\IA_Investigacion\Deteccion_Corrupcion")

DATA_EXT = BASE / "data" / "external" / "obra"

# fallback para notebook temporal
ALT_BASE = Path("/mnt/data")

FILES_OBRA = {
    "o1a": "DS_DASH_Obra_1A.csv",
    "o2a3a": "DS_DASH_Obra_2A_3A.csv",
    "o2b": "DS_DASH_Obra_2B.csv",
    "o3b": "DS_DASH_Obra_3B.csv",
    "o3c": "DS_DASH_Obra_3C.csv",
    "o4a": "DS_DASH_Obra_4A.csv",
    "o4b": "DS_DASH_Obra_4B.csv",
    "o5a": "DS_DASH_Obra_5A.csv",
}


def read_csv_robust(path: Path) -> pd.DataFrame:

    encodings = [
        "utf-8",
        "utf-8-sig",
        "latin1",
        "cp1252",
    ]

    last_error = None

    for enc in encodings:
        try:
            df = pd.read_csv(path, encoding=enc)
            df.attrs["encoding"] = enc
            return df
        except Exception as exc:
            last_error = exc

    raise last_error


def normalize_cols(df: pd.DataFrame) -> pd.DataFrame:

    out = df.copy()

    out.columns = (
        out.columns.astype(str)
        .str.strip()
        .str.replace("\ufeff", "", regex=False)
        .str.replace(" ", "_", regex=False)
        .str.upper()
    )

    return out


tablas_obra = {}

for key, fname in FILES_OBRA.items():

    path = DATA_EXT / fname

    if not path.exists():

        alt = ALT_BASE / fname

        if alt.exists():
            path = alt

    print("=" * 100)
    print(f"{key} -> {fname}")
    print("=" * 100)

    df = read_csv_robust(path)
    df = normalize_cols(df)

    tablas_obra[key] = df

    print("Shape:", df.shape)
    print("Encoding:", df.attrs.get("encoding"))

    print("\nColumnas:")
    for c in df.columns:
        print("-", c)

    print("\nPrimeras filas:")
    display(df.head(3))

====================================================================================================
o1a -> DS_DASH_Obra_1A.csv
====================================================================================================
Shape: (326, 12)
Encoding: latin1

Columnas:
- CODIGO_UNICO
- SECTOR
- DEPARTAMENTO
- NIVEL_GOBIERNO
- IDENTIFICADOR_OBRA
- PROCESO
- OBJETO_PROCESO
- CODIGO_OBRA
- NOMBREOBRA
- METODO_CONTRATACION
- TIEMPO_ABSOLUCION_CONSULTAS
- TIEMPO_PRESENTACION_OFERTAS

Primeras filas:

,CODIGO_UNICO,SECTOR,DEPARTAMENTO,NIVEL_GOBIERNO,IDENTIFICADOR_OBRA,PROCESO,OBJETO_PROCESO,CODIGO_OBRA,NOMBREOBRA,METODO_CONTRATACION,TIEMPO_ABSOLUCION_CONSULTAS,TIEMPO_PRESENTACION_OFERTAS
0,2002060,TRANSPORTE,MULTIDEPARTAMENTAL,GOBIERNO NACIONAL,2002060-2434-702592-2064311-19777,3,Consultoría de Obra,19777,Obra Carretera Puente Chino - Aguaytía; sector...,Concurso Público,0,0
1,2002210,TRANSPORTE,MULTIDEPARTAMENTAL,GOBIERNO NACIONAL,2002210-8880-869397-2169938-826,60,Consultoría de Obra,826,Rehabilitación y Mejoramiento de la Carretera ...,Concurso Público,0,0
2,2002210,TRANSPORTE,MULTIDEPARTAMENTAL,GOBIERNO NACIONAL,2002210-8880-870112-2169901-826,60,Consultoría de Obra,826,Rehabilitación y Mejoramiento de la Carretera ...,Concurso Público,0,0

====================================================================================================
o2a3a -> DS_DASH_Obra_2A_3A.csv
====================================================================================================
Shape: (552, 22)
Encoding: latin1

Columnas:
- CODIGO_UNICO
- SECTOR
- DEPARTAMENTO
- NIVEL_GOBIERNO
- IDENTIFICADOR_OBRA
- PROCESO
- OBJETO_PROCESO
- CODIGO_OBRA
- NOMBREOBRA
- METODO_CONTRATACION
- TIEMPO_ABSOLUCION_CONSULTAS
- TIEMPO_PRESENTACION_OFERTAS
- CODIGO_RUC
- RAZON_SOCIAL
- CONVOCATORIA_PROCESO_GANADO
- MIEMBROS_DE_COMITE
- TOTALPROCESOSPARTICIPANTES
- CODIGO_CONTRATO
- NUMERO_CONTRATO
- MONTO_CONTRACTUAL
- MONTO_REFERENCIAL
- MONTO_OFERTADO_PROMEDIO

Primeras filas:

,CODIGO_UNICO,SECTOR,DEPARTAMENTO,NIVEL_GOBIERNO,IDENTIFICADOR_OBRA,PROCESO,OBJETO_PROCESO,CODIGO_OBRA,NOMBREOBRA,METODO_CONTRATACION,...,CODIGO_RUC,RAZON_SOCIAL,CONVOCATORIA_PROCESO_GANADO,MIEMBROS_DE_COMITE,TOTALPROCESOSPARTICIPANTES,CODIGO_CONTRATO,NUMERO_CONTRATO,MONTO_CONTRACTUAL,MONTO_REFERENCIAL,MONTO_OFERTADO_PROMEDIO
0,2002060,TRANSPORTE,MULTIDEPARTAMENTAL,GOBIERNO NACIONAL,2002060-2434-702592-2064311-19777,3,Consultoría de Obra,19777,Obra Carretera Puente Chino - Aguaytía; sector...,Concurso Público,...,20549322434,PYUNGHWA ENGINEERING CONSULTANTS LTDA SUCURSAL...,702592,"ALVARADO CALDERON CESAR DANIEL , Cotos Perez ...",81,2064311,063-2021-MTC/20.2,2235852.56,2484280.62,2276555.18
1,2002210,TRANSPORTE,MULTIDEPARTAMENTAL,GOBIERNO NACIONAL,2002210-8880-869397-2169938-826,60,Consultoría de Obra,826,Rehabilitación y Mejoramiento de la Carretera ...,Concurso Público,...,20522404331,PRW INGENIERIA Y CONSTRUCCION S.A.C.,869397,"CERVANTES CHICLLA REY PABLO, LESCANO AVALOS D...",123,2169938,022-2023-MTC/20.2,331016.99,367796.65,331168.22
2,2002210,TRANSPORTE,MULTIDEPARTAMENTAL,GOBIERNO NACIONAL,2002210-8880-870112-2169901-826,60,Consultoría de Obra,826,Rehabilitación y Mejoramiento de la Carretera ...,Concurso Público,...,20528975055,CONSTRUCTORA & CONSULTORA SAHMAT SOCIEDAD COME...,870112,"CERVANTES CHICLLA REY PABLO, LESCANO AVALOS D...",181,2169901,015-2023-MTC/20.2,283575.23,315083.58,284563.66

====================================================================================================
o2b -> DS_DASH_Obra_2B.csv
====================================================================================================
Shape: (1613, 6)
Encoding: latin1

Columnas:
- CODIGO_UNICO
- IDENTIFICADOR_OBRA
- PROCESO
- CONVOCATORIA
- DNI_MIEMBRO_COMITE
- NOMBRE_MIEMBRO_COMITE

Primeras filas:

,CODIGO_UNICO,IDENTIFICADOR_OBRA,PROCESO,CONVOCATORIA,DNI_MIEMBRO_COMITE,NOMBRE_MIEMBRO_COMITE
0,2002060,2002060-2434-702592-2064311-19777,3,702592,21461664,ESQUIVEL CERON LUZ YOLANDA
1,2002060,2002060-2434-702592-2064311-19777,3,702592,32977736,Cotos Perez Hugo Antonio
2,2002060,2002060-2434-702592-2064311-19777,3,702592,41798624,MANCHA CASO FREDDY

====================================================================================================
o3b -> DS_DASH_Obra_3B.csv
====================================================================================================
Shape: (5249, 20)
Encoding: latin1

Columnas:
- CODIGO_UNICO
- SECTOR
- DEPARTAMENTO
- NIVEL_GOBIERNO
- IDENTIFICADOR_OBRA
- PROCESO
- OBJETO_PROCESO
- CODIGO_OBRA
- NOMBREOBRA
- METODO_CONTRATACION
- TIEMPO_ABSOLUCION_CONSULTAS
- TIEMPO_PRESENTACION_OFERTAS
- CODIGO_RUC_GANADOR
- RAZON_SOCIAL
- CONVOCATORIA_PROCESO_GANADO
- TOTALPROCESOSPARTICIPANTES
- CODIGO_CONTRATO
- NUMERO_CONTRATO
- CODIGO_RUC_PARTICIPANTE
- NOMBRE_PARTICIPANTE

Primeras filas:

,CODIGO_UNICO,SECTOR,DEPARTAMENTO,NIVEL_GOBIERNO,IDENTIFICADOR_OBRA,PROCESO,OBJETO_PROCESO,CODIGO_OBRA,NOMBREOBRA,METODO_CONTRATACION,TIEMPO_ABSOLUCION_CONSULTAS,TIEMPO_PRESENTACION_OFERTAS,CODIGO_RUC_GANADOR,RAZON_SOCIAL,CONVOCATORIA_PROCESO_GANADO,TOTALPROCESOSPARTICIPANTES,CODIGO_CONTRATO,NUMERO_CONTRATO,CODIGO_RUC_PARTICIPANTE,NOMBRE_PARTICIPANTE
0,2002060,TRANSPORTE,MULTIDEPARTAMENTAL,GOBIERNO NACIONAL,2002060-2434-702592-2064311-19777,3,Consultoría de Obra,19777,Obra Carretera Puente Chino - Aguaytía; sector...,Concurso Público,0,0,20549322434,VERA & MORENO S.A. CONSULTORES DE INGENIERIA(*),702592,81,2064311,063-2021-MTC/20.2,20137109612,VERA & MORENO S.A. CONSULTORES DE INGENIERIA(*)
1,2002060,TRANSPORTE,MULTIDEPARTAMENTAL,GOBIERNO NACIONAL,2002060-2434-702592-2064311-19777,3,Consultoría de Obra,19777,Obra Carretera Puente Chino - Aguaytía; sector...,Concurso Público,0,0,20549322434,PROMOCION Y GESTION PROMOGEST SOCIEDAD ANONIMA...,702592,81,2064311,063-2021-MTC/20.2,20511668094,PROMOCION Y GESTION PROMOGEST SOCIEDAD ANONIMA...
2,2002060,TRANSPORTE,MULTIDEPARTAMENTAL,GOBIERNO NACIONAL,2002060-2434-702592-2064311-19777,3,Consultoría de Obra,19777,Obra Carretera Puente Chino - Aguaytía; sector...,Concurso Público,0,0,20549322434,URCI CONSULTORES S.L. SUCURSAL DEL PERU,702592,81,2064311,063-2021-MTC/20.2,20524383901,URCI CONSULTORES S.L. SUCURSAL DEL PERU

====================================================================================================
o3c -> DS_DASH_Obra_3C.csv
====================================================================================================
Shape: (5249, 8)
Encoding: latin1

Columnas:
- NUMERO_CONTRATO
- CODIGO_CONTRATO
- IDENTIFICADOR_OBRA
- NOMBRE_EMPRESA_GANADORA
- RUC_GANADOR
- RUC_PARTICIPANTE
- NOMBRE_EMPRESA_PARTICIPANTE
- MONTO_OFERTADO

Primeras filas:

,NUMERO_CONTRATO,CODIGO_CONTRATO,IDENTIFICADOR_OBRA,NOMBRE_EMPRESA_GANADORA,RUC_GANADOR,RUC_PARTICIPANTE,NOMBRE_EMPRESA_PARTICIPANTE,MONTO_OFERTADO
0,"C.C. O, PARA LA SUPERVICION DE ELABORACION DE ...",2099542,2428356-2428356-767107-2099542-152016,DEXTRE MORIMOTO EDUARDO RAUL(*),10101999039,10101999039,DEXTRE MORIMOTO EDUARDO RAUL,653894.5
1,"C.C. O, PARA LA SUPERVICION DE ELABORACION DE ...",2099542,2428356-2428356-767107-2099542-152016,DEXTRE MORIMOTO EDUARDO RAUL(*),10101999039,10181420761,VELARDE SAGASTEGUI JUAN STALIN(*),653894.5
2,"C.C. O, PARA LA SUPERVICION DE ELABORACION DE ...",2099542,2428356-2428356-767107-2099542-152016,DEXTRE MORIMOTO EDUARDO RAUL(*),10101999039,20508114096,CAYSA ASOCIADOS S.A.C.,653894.5

====================================================================================================
o4a -> DS_DASH_Obra_4A.csv
====================================================================================================
Shape: (326, 9)
Encoding: latin1

Columnas:
- CODIGO_UNICO
- SECTOR
- DEPARTAMENTO
- NIVEL_GOBIERNO
- CODIGO_OBRA
- NOMBRE_OBRA
- EMPRESA_EJECUTORA
- EMPRESA_SUPERVISORA
- ESTADO_OBRA

Primeras filas:

,CODIGO_UNICO,SECTOR,DEPARTAMENTO,NIVEL_GOBIERNO,CODIGO_OBRA,NOMBRE_OBRA,EMPRESA_EJECUTORA,EMPRESA_SUPERVISORA,ESTADO_OBRA
0,2331873,TRABAJO,MULTIDEPARTAMENTAL,GOBIERNO REGIONAL,102021,MEJORAMIENTO DEL SERVICIO DE TRANSITABILIDAD D...,NaN,CONSORCIO SUPERVISOR PUENTE PACCHA;TICONA VARG...,Finalizado
1,2331873,TRABAJO,MULTIDEPARTAMENTAL,GOBIERNO REGIONAL,102022,MEJORAMIENTO DEL SERVICIO DE TRANSITABILIDAD D...,NaN,FERNANDEZ IDROGO SEGUNDO GRIMANIEL,Finalizado
2,2233958,TRANSPORTE,MULTIDEPARTAMENTAL,GOBIERNO NACIONAL,102591,CONSTRUCCIÓN PUENTE HUALLAGA Y ACCESOS,NaN,NaN,En Ejecución

====================================================================================================
o4b -> DS_DASH_Obra_4B.csv
====================================================================================================
Shape: (326, 15)
Encoding: latin1

Columnas:
- CODIGO_UNICO
- SECTOR
- DEPARTAMENTO
- NIVEL_GOBIERNO
- IDENTIFICADOR_OBRA
- CODIGO_OBRA
- NOMBRE_OBRA
- ESTADO_OBRA
- ETAPA
- DIAS_PLAZO
- TOTAL_CONTROL_PREVIO
- TOTAL_CONTROL_SIMULTANEO
- TOTAL_CONTROL_POSTERIOR
- RIESGO_OBRA
- RIESGO_DESCRIPCION_OBRA

Primeras filas:

,CODIGO_UNICO,SECTOR,DEPARTAMENTO,NIVEL_GOBIERNO,IDENTIFICADOR_OBRA,CODIGO_OBRA,NOMBRE_OBRA,ESTADO_OBRA,ETAPA,DIAS_PLAZO,TOTAL_CONTROL_PREVIO,TOTAL_CONTROL_SIMULTANEO,TOTAL_CONTROL_POSTERIOR,RIESGO_OBRA,RIESGO_DESCRIPCION_OBRA
0,2002060,TRANSPORTE,MULTIDEPARTAMENTAL,GOBIERNO NACIONAL,2002060-2434-702592-2064311-19777,19777,Obra Carretera Puente Chino - Aguaytía; sector...,Finalizado,ESTUDIO DEFINITIVO,0,0,0,0,4,Extremadamente Riesgosa
1,2002210,TRANSPORTE,MULTIDEPARTAMENTAL,GOBIERNO NACIONAL,2002210-8880-869397-2169938-826,826,Rehabilitación y Mejoramiento de la Carretera ...,En Ejecución,ETAPA NO IDENTIFICADA,0,0,0,0,2,Medianamente Riesgosa
2,2002210,TRANSPORTE,MULTIDEPARTAMENTAL,GOBIERNO NACIONAL,2002210-8880-870112-2169901-826,826,Rehabilitación y Mejoramiento de la Carretera ...,En Ejecución,ETAPA NO IDENTIFICADA,0,0,0,0,2,Medianamente Riesgosa

====================================================================================================
o5a -> DS_DASH_Obra_5A.csv
====================================================================================================
Shape: (634, 15)
Encoding: latin1

Columnas:
- CODIGO_UNICO
- SECTOR
- DEPARTAMENTO
- NIVEL_GOBIERNO
- IDENTIFICADOR_OBRA
- ANHO
- MES
- PLANIFICADO
- REAL
- IND_INTERVENSION
- IND_RESIDENTE
- IND_MONTO_ADELANTO_MATERIALES
- IND_MONTO_ADELANTO_DIRECTO
- IND_FECHA_ADELANTO_MATERIALES
- IND_FECHA_ADELANTO_DIRECTO

Primeras filas:

,CODIGO_UNICO,SECTOR,DEPARTAMENTO,NIVEL_GOBIERNO,IDENTIFICADOR_OBRA,ANHO,MES,PLANIFICADO,REAL,IND_INTERVENSION,IND_RESIDENTE,IND_MONTO_ADELANTO_MATERIALES,IND_MONTO_ADELANTO_DIRECTO,IND_FECHA_ADELANTO_MATERIALES,IND_FECHA_ADELANTO_DIRECTO
0,2331873,TRABAJO,MULTIDEPARTAMENTAL,GOBIERNO REGIONAL,2331873-371182-638870-2023471-102021,NaN,NaN,0.0,0.00,NORMAL,NORMAL,NORMAL,NORMAL,NORMAL,NORMAL
1,2331873,TRABAJO,MULTIDEPARTAMENTAL,GOBIERNO REGIONAL,2331873-371182-670830-2045952-102022,NaN,NaN,0.0,0.00,NORMAL,NORMAL,NORMAL,NORMAL,NORMAL,NORMAL
2,2233958,TRANSPORTE,MULTIDEPARTAMENTAL,GOBIERNO NACIONAL,2233958-4588-516149-2047423-102591,2023.0,3.0,1.0,0.76,NORMAL,NORMAL,NORMAL,NORMAL,NORMAL,NORMAL

### Paso 2: análisis de llaves y relaciones

##### 2.1 — ANALIZAR UNICIDAD DE LLAVES

In [2]:
# ===============================
# PASO 2.1: UNICIDAD DE LLAVES
# ===============================

candidate_keys = [
    "CODIGO_UNICO",
    "IDENTIFICADOR_OBRA",
    "CODIGO_OBRA",
]

rows = []

for key_df, df in tablas_obra.items():

    total_rows = len(df)

    for col in candidate_keys:

        if col not in df.columns:
            continue

        nunique = df[col].nunique(dropna=True)

        rows.append({
            "tabla": key_df,
            "columna": col,
            "rows": total_rows,
            "n_unicos": nunique,
            "pct_unicidad": round(
                nunique / total_rows * 100,
                2
            )
        })

keys_df = pd.DataFrame(rows)

display(
    keys_df.sort_values(
        ["tabla", "pct_unicidad"],
        ascending=[True, False]
    )
)

    tabla             columna  rows  n_unicos  pct_unicidad
1     o1a  IDENTIFICADOR_OBRA   326       326        100.00
2     o1a         CODIGO_OBRA   326       232         71.17
0     o1a        CODIGO_UNICO   326       170         52.15
4   o2a3a  IDENTIFICADOR_OBRA   552       324         58.70
5   o2a3a         CODIGO_OBRA   552       230         41.67
3   o2a3a        CODIGO_UNICO   552       168         30.43
7     o2b  IDENTIFICADOR_OBRA  1613       259         16.06
6     o2b        CODIGO_UNICO  1613       125          7.75
9     o3b  IDENTIFICADOR_OBRA  5249       324          6.17
10    o3b         CODIGO_OBRA  5249       230          4.38
8     o3b        CODIGO_UNICO  5249       168          3.20
11    o3c  IDENTIFICADOR_OBRA  5249       324          6.17
13    o4a         CODIGO_OBRA   326       232         71.17
12    o4a        CODIGO_UNICO   326       170         52.15
15    o4b  IDENTIFICADOR_OBRA   326       326        100.00
16    o4b         CODIGO_OBRA   326       232         71.17
14    o4b        CODIGO_UNICO   326       170         52.15
18    o5a  IDENTIFICADOR_OBRA   634       326         51.42
17    o5a        CODIGO_UNICO   634       170         26.81

##### 2.2 — DETECTAR DUPLICADOS

In [3]:
# ===============================
# PASO 2.2: DUPLICADOS
# ===============================

for key_df, df in tablas_obra.items():

    print("\n" + "=" * 100)
    print(f"TABLA: {key_df}")
    print("=" * 100)

    for col in candidate_keys:

        if col not in df.columns:
            continue

        dup = (
            df[col]
            .value_counts(dropna=False)
            .reset_index()
        )

        dup.columns = [col, "conteo"]

        repeated = dup[dup["conteo"] > 1]

        print(f"\n{col}")
        print("-" * 40)

        print("Valores únicos:", df[col].nunique(dropna=True))
        print("Repetidos:", len(repeated))

        if len(repeated) > 0:
            display(repeated.head(10))

====================================================================================================
TABLA: o1a
====================================================================================================

CODIGO_UNICO
----------------------------------------
Valores únicos: 170
Repetidos: 73

   CODIGO_UNICO  conteo
0       2344004      17
1       2233850      14
2       2425240      13
3       2193247      12
4       2343984      10
5       2234473       9
6       2331873       6
7       2031000       5
8       2194709       4
9       2386120       4

IDENTIFICADOR_OBRA
----------------------------------------
Valores únicos: 326
Repetidos: 0

CODIGO_OBRA
----------------------------------------
Valores únicos: 232
Repetidos: 77

   CODIGO_OBRA  conteo
0        76727       9
1       141153       6
2        79281       4
3        77795       3
4       108917       3
5        33536       3
6       140616       3
7          826       2
8       130180       2
9        72873       2

====================================================================================================
TABLA: o2a3a
====================================================================================================

CODIGO_UNICO
----------------------------------------
Valores únicos: 168
Repetidos: 111

   CODIGO_UNICO  conteo
0       2425240      47
1       2233850      24
2       2344004      23
3       2193247      22
4       2234473      16
5       2331873      13
6       2343984      12
7       2031000       7
8       2386120       7
9       2412703       7

IDENTIFICADOR_OBRA
----------------------------------------
Valores únicos: 324
Repetidos: 167

                      IDENTIFICADOR_OBRA  conteo
0  2425240-2425240-643287-2025634-129257       7
1  2425240-2425240-644176-2047150-129392       7
2  2425240-2425240-656768-2020868-130759       7
3  2425240-2425240-649683-2019501-130452       6
4  2489058-2489058-891853-2187416-500659       5
5    2080694-77545-673882-2038678-134497       4
6  2425240-2425240-654909-2017911-131543       4
7  2412703-2412703-819493-2184883-161132       4
8  2382880-2382880-783281-2120097-157653       4
9   2193247-280513-698718-2061957-108914       4

CODIGO_OBRA
----------------------------------------
Valores únicos: 230
Repetidos: 154

   CODIGO_OBRA  conteo
0        76727      16
1       141153      11
2        79281       9
3       130759       8
4       108914       7
5       129392       7
6       129257       7
7       500659       7
8       130452       6
9       157653       6

====================================================================================================
TABLA: o2b
====================================================================================================

CODIGO_UNICO
----------------------------------------
Valores únicos: 125
Repetidos: 125

   CODIGO_UNICO  conteo
0       2344004     116
1       2425240      82
2       2193247      66
3       2343984      62
4       2234473      55
5       2233850      48
6       2331873      37
7       2031000      30
8       2386120      24
9       2329618      22

IDENTIFICADOR_OBRA
----------------------------------------
Valores únicos: 259
Repetidos: 259

                      IDENTIFICADOR_OBRA  conteo
0    2055893-48520-680485-2044147-118093      13
1    2084815-74176-865826-2173901-174311      12
2    2281442-324555-911561-2199221-61561      11
3  2346750-2346750-855158-2172532-169751      11
4   2194709-231989-739211-2108440-141104      11
5  2427358-2427358-881574-2182436-169628      11
6   2344004-382572-809167-2135355-156613      10
7  2555903-2555903-896909-2184770-176267      10
8   2344004-382572-803024-2127961-156612      10
9  2560253-2560253-873027-2175066-176993      10

====================================================================================================
TABLA: o3b
====================================================================================================

CODIGO_UNICO
----------------------------------------
Valores únicos: 168
Repetidos: 135

   CODIGO_UNICO  conteo
0       2425240    1549
1       2193247     619
2       2282760     126
3       2331873     110
4       2234473     105
5       2233958      90
6       2234988      83
7       2386120      68
8       2233850      68
9       2066003      67

IDENTIFICADOR_OBRA
----------------------------------------
Valores únicos: 324
Repetidos: 252

                      IDENTIFICADOR_OBRA  conteo
0  2425240-2425240-656768-2020868-130759     287
1  2425240-2425240-649683-2019501-130452     270
2  2425240-2425240-643287-2025634-129257     259
3  2425240-2425240-644176-2047150-129392     238
4  2425240-2425240-654909-2017911-131543     204
5   2193247-280513-698718-2061957-108914     172
6  2425240-2425240-654896-2016762-131498     126
7  2425240-2425240-649549-2013506-129613      84
8    2282760-172973-688300-2045681-47658      78
9   2193247-280513-708529-2062106-108914      69

CODIGO_OBRA
----------------------------------------
Valores únicos: 230
Repetidos: 189

   CODIGO_OBRA  conteo
0       130759     294
1       130452     270
2       129257     259
3       108914     241
4       129392     238
5       131543     226
6       108916     130
7       131498     126
8       108912     110
9       108917     106

====================================================================================================
TABLA: o3c
====================================================================================================

IDENTIFICADOR_OBRA
----------------------------------------
Valores únicos: 324
Repetidos: 252

                      IDENTIFICADOR_OBRA  conteo
0  2425240-2425240-656768-2020868-130759     287
1  2425240-2425240-649683-2019501-130452     270
2  2425240-2425240-643287-2025634-129257     259
3  2425240-2425240-644176-2047150-129392     238
4  2425240-2425240-654909-2017911-131543     204
5   2193247-280513-698718-2061957-108914     172
6  2425240-2425240-654896-2016762-131498     126
7  2425240-2425240-649549-2013506-129613      84
8    2282760-172973-688300-2045681-47658      78
9   2193247-280513-708529-2062106-108914      69

====================================================================================================
TABLA: o4a
====================================================================================================

CODIGO_UNICO
----------------------------------------
Valores únicos: 170
Repetidos: 73

   CODIGO_UNICO  conteo
0       2344004      17
1       2233850      14
2       2425240      13
3       2193247      12
4       2343984      10
5       2234473       9
6       2331873       6
7       2031000       5
8       2194709       4
9       2386120       4

CODIGO_OBRA
----------------------------------------
Valores únicos: 232
Repetidos: 77

   CODIGO_OBRA  conteo
0        76727       9
1       141153       6
2        79281       4
3       108917       3
4        33536       3
5        77795       3
6       140616       3
7       108912       2
8       124333       2
9       126280       2

====================================================================================================
TABLA: o4b
====================================================================================================

CODIGO_UNICO
----------------------------------------
Valores únicos: 170
Repetidos: 73

   CODIGO_UNICO  conteo
0       2344004      17
1       2233850      14
2       2425240      13
3       2193247      12
4       2343984      10
5       2234473       9
6       2331873       6
7       2031000       5
8       2194709       4
9       2386120       4

IDENTIFICADOR_OBRA
----------------------------------------
Valores únicos: 326
Repetidos: 0

CODIGO_OBRA
----------------------------------------
Valores únicos: 232
Repetidos: 77

   CODIGO_OBRA  conteo
0        76727       9
1       141153       6
2        79281       4
3        77795       3
4       108917       3
5        33536       3
6       140616       3
7          826       2
8       130180       2
9        72873       2

====================================================================================================
TABLA: o5a
====================================================================================================

CODIGO_UNICO
----------------------------------------
Valores únicos: 170
Repetidos: 83

   CODIGO_UNICO  conteo
0       2344004      49
1       2193247      34
2       2343984      31
3       2233850      26
4       2305241      16
5       2164051      15
6       2158700      14
7       2196451      14
8       2177209      14
9       2192219      14

IDENTIFICADOR_OBRA
----------------------------------------
Valores únicos: 326
Repetidos: 66

                      IDENTIFICADOR_OBRA  conteo
0  2387810-2387810-582351-2173525-115304       9
1   2344004-382572-775404-2139241-156613       8
2     2403504-95668-887027-2180323-83650       8
3     2166858-10703-786923-2119129-61095       8
4    2305241-177553-686493-2087875-51734       8
5   2344004-382572-809167-2135355-156613       8
6    2305241-177553-686451-2070820-51734       8
7   2329618-365930-776041-2105638-150346       8
8   2300016-314709-739838-2085159-138996       7
9   2284956-303267-727717-2096706-138999       7

##### 2.3 — RELACIONES ENTRE LLAVES

In [4]:
# ===============================
# PASO 2.3: RELACIONES ENTRE LLAVES
# ===============================

def analyze_relation(df, left, right):

    if left not in df.columns or right not in df.columns:
        return None

    rel = (
        df.groupby(left)[right]
        .nunique()
        .describe()
        .to_frame("stats")
    )

    return rel


relation_pairs = [
    ("CODIGO_UNICO", "IDENTIFICADOR_OBRA"),
    ("IDENTIFICADOR_OBRA", "CODIGO_OBRA"),
    ("CODIGO_UNICO", "CODIGO_OBRA"),
]

for key_df, df in tablas_obra.items():

    print("\n" + "=" * 100)
    print(f"TABLA: {key_df}")
    print("=" * 100)

    for left, right in relation_pairs:

        if left not in df.columns or right not in df.columns:
            continue

        print(f"\n{left} -> {right}")

        rel = (
            df.groupby(left)[right]
            .nunique()
        )

        print(rel.describe())

        print("\nTop relaciones múltiples:")

        display(
            rel[rel > 1]
            .sort_values(ascending=False)
            .head(10)
            .to_frame("n_relaciones")
        )

====================================================================================================
TABLA: o1a
====================================================================================================

CODIGO_UNICO -> IDENTIFICADOR_OBRA
count    170.000000
mean       1.917647
std        2.233218
min        1.000000
25%        1.000000
50%        1.000000
75%        2.000000
max       17.000000
Name: IDENTIFICADOR_OBRA, dtype: float64

Top relaciones múltiples:

              n_relaciones
CODIGO_UNICO
2344004                 17
2233850                 14
2425240                 13
2193247                 12
2343984                 10
2234473                  9
2331873                  6
2031000                  5
2194709                  4
2386120                  4

IDENTIFICADOR_OBRA -> CODIGO_OBRA
count    326.0
mean       1.0
std        0.0
min        1.0
25%        1.0
50%        1.0
75%        1.0
max        1.0
Name: CODIGO_OBRA, dtype: float64

Top relaciones múltiples:

Empty DataFrame
Columns: [n_relaciones]
Index: []

CODIGO_UNICO -> CODIGO_OBRA
count    170.000000
mean       1.364706
std        1.370415
min        1.000000
25%        1.000000
50%        1.000000
75%        1.000000
max       11.000000
Name: CODIGO_OBRA, dtype: float64

Top relaciones múltiples:

              n_relaciones
CODIGO_UNICO
2344004                 11
2425240                 11
2233850                  8
2343984                  7
2193247                  6
2194709                  3
2329618                  3
2331873                  3
2055893                  2
2031000                  2

====================================================================================================
TABLA: o2a3a
====================================================================================================

CODIGO_UNICO -> IDENTIFICADOR_OBRA
count    168.000000
mean       1.928571
std        2.244278
min        1.000000
25%        1.000000
50%        1.000000
75%        2.000000
max       17.000000
Name: IDENTIFICADOR_OBRA, dtype: float64

Top relaciones múltiples:

              n_relaciones
CODIGO_UNICO
2344004                 17
2233850                 14
2425240                 13
2193247                 12
2343984                 10
2234473                  9
2331873                  6
2031000                  5
2194709                  4
2386120                  4

IDENTIFICADOR_OBRA -> CODIGO_OBRA
count    324.0
mean       1.0
std        0.0
min        1.0
25%        1.0
50%        1.0
75%        1.0
max        1.0
Name: CODIGO_OBRA, dtype: float64

Top relaciones múltiples:

Empty DataFrame
Columns: [n_relaciones]
Index: []

CODIGO_UNICO -> CODIGO_OBRA
count    168.000000
mean       1.369048
std        1.378012
min        1.000000
25%        1.000000
50%        1.000000
75%        1.000000
max       11.000000
Name: CODIGO_OBRA, dtype: float64

Top relaciones múltiples:

              n_relaciones
CODIGO_UNICO
2344004                 11
2425240                 11
2233850                  8
2343984                  7
2193247                  6
2194709                  3
2329618                  3
2331873                  3
2055893                  2
2031000                  2

====================================================================================================
TABLA: o2b
====================================================================================================

CODIGO_UNICO -> IDENTIFICADOR_OBRA
count    125.000000
mean       2.072000
std        2.505401
min        1.000000
25%        1.000000
50%        1.000000
75%        2.000000
max       17.000000
Name: IDENTIFICADOR_OBRA, dtype: float64

Top relaciones múltiples:

              n_relaciones
CODIGO_UNICO
2344004                 17
2233850                 14
2425240                 13
2193247                 11
2343984                 10
2234473                  9
2331873                  6
2031000                  5
2386120                  4
2329618                  3

====================================================================================================
TABLA: o3b
====================================================================================================

CODIGO_UNICO -> IDENTIFICADOR_OBRA
count    168.000000
mean       1.928571
std        2.244278
min        1.000000
25%        1.000000
50%        1.000000
75%        2.000000
max       17.000000
Name: IDENTIFICADOR_OBRA, dtype: float64

Top relaciones múltiples:

              n_relaciones
CODIGO_UNICO
2344004                 17
2233850                 14
2425240                 13
2193247                 12
2343984                 10
2234473                  9
2331873                  6
2031000                  5
2194709                  4
2386120                  4

IDENTIFICADOR_OBRA -> CODIGO_OBRA
count    324.0
mean       1.0
std        0.0
min        1.0
25%        1.0
50%        1.0
75%        1.0
max        1.0
Name: CODIGO_OBRA, dtype: float64

Top relaciones múltiples:

Empty DataFrame
Columns: [n_relaciones]
Index: []

CODIGO_UNICO -> CODIGO_OBRA
count    168.000000
mean       1.369048
std        1.378012
min        1.000000
25%        1.000000
50%        1.000000
75%        1.000000
max       11.000000
Name: CODIGO_OBRA, dtype: float64

Top relaciones múltiples:

              n_relaciones
CODIGO_UNICO
2344004                 11
2425240                 11
2233850                  8
2343984                  7
2193247                  6
2194709                  3
2329618                  3
2331873                  3
2055893                  2
2031000                  2

====================================================================================================
TABLA: o3c
====================================================================================================

====================================================================================================
TABLA: o4a
====================================================================================================

CODIGO_UNICO -> CODIGO_OBRA
count    170.000000
mean       1.364706
std        1.370415
min        1.000000
25%        1.000000
50%        1.000000
75%        1.000000
max       11.000000
Name: CODIGO_OBRA, dtype: float64

Top relaciones múltiples:

              n_relaciones
CODIGO_UNICO
2344004                 11
2425240                 11
2233850                  8
2343984                  7
2193247                  6
2194709                  3
2329618                  3
2331873                  3
2055893                  2
2031000                  2

====================================================================================================
TABLA: o4b
====================================================================================================

CODIGO_UNICO -> IDENTIFICADOR_OBRA
count    170.000000
mean       1.917647
std        2.233218
min        1.000000
25%        1.000000
50%        1.000000
75%        2.000000
max       17.000000
Name: IDENTIFICADOR_OBRA, dtype: float64

Top relaciones múltiples:

              n_relaciones
CODIGO_UNICO
2344004                 17
2233850                 14
2425240                 13
2193247                 12
2343984                 10
2234473                  9
2331873                  6
2031000                  5
2194709                  4
2386120                  4

IDENTIFICADOR_OBRA -> CODIGO_OBRA
count    326.0
mean       1.0
std        0.0
min        1.0
25%        1.0
50%        1.0
75%        1.0
max        1.0
Name: CODIGO_OBRA, dtype: float64

Top relaciones múltiples:

Empty DataFrame
Columns: [n_relaciones]
Index: []

CODIGO_UNICO -> CODIGO_OBRA
count    170.000000
mean       1.364706
std        1.370415
min        1.000000
25%        1.000000
50%        1.000000
75%        1.000000
max       11.000000
Name: CODIGO_OBRA, dtype: float64

Top relaciones múltiples:

              n_relaciones
CODIGO_UNICO
2344004                 11
2425240                 11
2233850                  8
2343984                  7
2193247                  6
2194709                  3
2329618                  3
2331873                  3
2055893                  2
2031000                  2

====================================================================================================
TABLA: o5a
====================================================================================================

CODIGO_UNICO -> IDENTIFICADOR_OBRA
count    170.000000
mean       1.917647
std        2.233218
min        1.000000
25%        1.000000
50%        1.000000
75%        2.000000
max       17.000000
Name: IDENTIFICADOR_OBRA, dtype: float64

Top relaciones múltiples:

              n_relaciones
CODIGO_UNICO
2344004                 17
2233850                 14
2425240                 13
2193247                 12
2343984                 10
2234473                  9
2331873                  6
2031000                  5
2194709                  4
2386120                  4

### PASO 3 — CONSTRUCCIÓN DE FEATURES AGREGADAS POR OBRA

##### 3.1 — FEATURES DE COMITÉ (o2b)

Objetivo. Construir señales tipo:
* cantidad de miembros
* cantidad de DNIs únicos
* densidad del comité

In [5]:
# ===============================
# PASO 3.1
# FEATURES COMITÉ (o2b)
# ===============================

df_o2b = tablas_obra["o2b"].copy()

print("Shape original:", df_o2b.shape)

display(df_o2b.head())


# ===============================
# NORMALIZAR
# ===============================

df_o2b["IDENTIFICADOR_OBRA"] = (
    df_o2b["IDENTIFICADOR_OBRA"]
    .astype(str)
    .str.strip()
)

df_o2b["DNI_MIEMBRO_COMITE"] = (
    df_o2b["DNI_MIEMBRO_COMITE"]
    .astype(str)
    .str.strip()
)


# ===============================
# FEATURES POR OBRA
# ===============================

feat_comite = (
    df_o2b
    .groupby("IDENTIFICADOR_OBRA")
    .agg(

        obra_n_miembros_comite=(
            "DNI_MIEMBRO_COMITE",
            "count"
        ),

        obra_n_dnis_comite_unicos=(
            "DNI_MIEMBRO_COMITE",
            "nunique"
        ),

        obra_n_convocatorias_comite=(
            "CONVOCATORIA",
            "nunique"
        ),

        obra_n_procesos_comite=(
            "PROCESO",
            "nunique"
        ),

    )
    .reset_index()
)

# ===============================
# FEATURE DERIVADA
# ===============================

feat_comite["obra_ratio_repeticion_comite"] = (
    feat_comite["obra_n_miembros_comite"]
    /
    feat_comite["obra_n_dnis_comite_unicos"]
)

print("Shape features comité:", feat_comite.shape)

display(feat_comite.head())

Shape original: (1613, 6)

,CODIGO_UNICO,IDENTIFICADOR_OBRA,PROCESO,CONVOCATORIA,DNI_MIEMBRO_COMITE,NOMBRE_MIEMBRO_COMITE
0,2002060,2002060-2434-702592-2064311-19777,3,702592,21461664,ESQUIVEL CERON LUZ YOLANDA
1,2002060,2002060-2434-702592-2064311-19777,3,702592,32977736,Cotos Perez Hugo Antonio
2,2002060,2002060-2434-702592-2064311-19777,3,702592,41798624,MANCHA CASO FREDDY
3,2002060,2002060-2434-702592-2064311-19777,3,702592,43584310,PIÑAN INDACOCHEA MARIA CECILIA
4,2002060,2002060-2434-702592-2064311-19777,3,702592,9382177,ROSALES LAURENTE ELKA CAROLINA

Shape features comité: (259, 6)

,IDENTIFICADOR_OBRA,obra_n_miembros_comite,obra_n_dnis_comite_unicos,obra_n_convocatorias_comite,obra_n_procesos_comite,obra_ratio_repeticion_comite
0,2002060-2434-702592-2064311-19777,6,6,1,1,1.0
1,2002210-8880-869397-2169938-826,6,6,1,1,1.0
2,2002210-8880-870112-2169901-826,6,6,1,1,1.0
3,2015918-1249-721938-2074791-45660,6,6,1,1,1.0
4,2026767-16256-709096-2067605-143536,6,6,1,1,1.0

### PASO 3.2 — FEATURES DE PARTICIPANTES (o3b)

OBJETIVO. Construir:
* n_participantes
* n_rucs_unicos
* n_contratos
* densidad participación

In [6]:
# ===============================
# PASO 3.2
# FEATURES PARTICIPANTES (o3b)
# ===============================

df_o3b = tablas_obra["o3b"].copy()

print("Shape original:", df_o3b.shape)

display(df_o3b.head())


# ===============================
# NORMALIZAR
# ===============================

for col in [
    "IDENTIFICADOR_OBRA",
    "CODIGO_RUC_PARTICIPANTE",
    "CODIGO_CONTRATO",
]:

    if col in df_o3b.columns:

        df_o3b[col] = (
            df_o3b[col]
            .astype(str)
            .str.strip()
        )


# ===============================
# FEATURES POR OBRA
# ===============================

feat_participantes = (
    df_o3b
    .groupby("IDENTIFICADOR_OBRA")
    .agg(

        obra_n_participaciones=(
            "CODIGO_RUC_PARTICIPANTE",
            "count"
        ),

        obra_n_rucs_participantes=(
            "CODIGO_RUC_PARTICIPANTE",
            "nunique"
        ),

        obra_n_contratos=(
            "CODIGO_CONTRATO",
            "nunique"
        ),

        obra_n_codigos_obra=(
            "CODIGO_OBRA",
            "nunique"
        ),

        obra_n_procesos=(
            "PROCESO",
            "nunique"
        ),

    )
    .reset_index()
)


# ===============================
# FEATURES DERIVADAS
# ===============================

feat_participantes["obra_ratio_participacion"] = (
    feat_participantes["obra_n_participaciones"]
    /
    feat_participantes["obra_n_rucs_participantes"]
)

feat_participantes["obra_ratio_contrato_participacion"] = (
    feat_participantes["obra_n_contratos"]
    /
    feat_participantes["obra_n_participaciones"]
)


print("Shape features participantes:", feat_participantes.shape)

display(feat_participantes.head())

display(
    feat_participantes.describe(include="all")
)

Shape original: (5249, 20)

,CODIGO_UNICO,SECTOR,DEPARTAMENTO,NIVEL_GOBIERNO,IDENTIFICADOR_OBRA,PROCESO,OBJETO_PROCESO,CODIGO_OBRA,NOMBREOBRA,METODO_CONTRATACION,TIEMPO_ABSOLUCION_CONSULTAS,TIEMPO_PRESENTACION_OFERTAS,CODIGO_RUC_GANADOR,RAZON_SOCIAL,CONVOCATORIA_PROCESO_GANADO,TOTALPROCESOSPARTICIPANTES,CODIGO_CONTRATO,NUMERO_CONTRATO,CODIGO_RUC_PARTICIPANTE,NOMBRE_PARTICIPANTE
0,2002060,TRANSPORTE,MULTIDEPARTAMENTAL,GOBIERNO NACIONAL,2002060-2434-702592-2064311-19777,3,Consultoría de Obra,19777,Obra Carretera Puente Chino - Aguaytía; sector...,Concurso Público,0,0,20549322434,VERA & MORENO S.A. CONSULTORES DE INGENIERIA(*),702592,81,2064311,063-2021-MTC/20.2,20137109612,VERA & MORENO S.A. CONSULTORES DE INGENIERIA(*)
1,2002060,TRANSPORTE,MULTIDEPARTAMENTAL,GOBIERNO NACIONAL,2002060-2434-702592-2064311-19777,3,Consultoría de Obra,19777,Obra Carretera Puente Chino - Aguaytía; sector...,Concurso Público,0,0,20549322434,PROMOCION Y GESTION PROMOGEST SOCIEDAD ANONIMA...,702592,81,2064311,063-2021-MTC/20.2,20511668094,PROMOCION Y GESTION PROMOGEST SOCIEDAD ANONIMA...
2,2002060,TRANSPORTE,MULTIDEPARTAMENTAL,GOBIERNO NACIONAL,2002060-2434-702592-2064311-19777,3,Consultoría de Obra,19777,Obra Carretera Puente Chino - Aguaytía; sector...,Concurso Público,0,0,20549322434,URCI CONSULTORES S.L. SUCURSAL DEL PERU,702592,81,2064311,063-2021-MTC/20.2,20524383901,URCI CONSULTORES S.L. SUCURSAL DEL PERU
3,2002060,TRANSPORTE,MULTIDEPARTAMENTAL,GOBIERNO NACIONAL,2002060-2434-702592-2064311-19777,3,Consultoría de Obra,19777,Obra Carretera Puente Chino - Aguaytía; sector...,Concurso Público,0,0,20549322434,PYUNGHWA ENGINEERING CONSULTANTS LTDA SUCURSAL...,702592,81,2064311,063-2021-MTC/20.2,20549322434,PYUNGHWA ENGINEERING CONSULTANTS LTDA SUCURSAL...
4,2002060,TRANSPORTE,MULTIDEPARTAMENTAL,GOBIERNO NACIONAL,2002060-2434-702592-2064311-19777,3,Consultoría de Obra,19777,Obra Carretera Puente Chino - Aguaytía; sector...,Concurso Público,0,0,20549322434,C & M CONSULTORES S.A.S SUCURSAL PERU,702592,81,2064311,063-2021-MTC/20.2,20602671110,C & M CONSULTORES S.A.S SUCURSAL PERU

Shape features participantes: (324, 8)

,IDENTIFICADOR_OBRA,obra_n_participaciones,obra_n_rucs_participantes,obra_n_contratos,obra_n_codigos_obra,obra_n_procesos,obra_ratio_participacion,obra_ratio_contrato_participacion
0,2002060-2434-702592-2064311-19777,6,6,1,1,1,1.0,0.166667
1,2002210-8880-869397-2169938-826,14,14,1,1,1,1.0,0.071429
2,2002210-8880-870112-2169901-826,13,13,1,1,1,1.0,0.076923
3,2026767-16256-709096-2067605-143536,20,10,1,1,1,2.0,0.050000
4,2027711-3876-682536-2050524-138320,23,23,1,1,1,1.0,0.043478

,IDENTIFICADOR_OBRA,obra_n_participaciones,obra_n_rucs_participantes,obra_n_contratos,obra_n_codigos_obra,obra_n_procesos,obra_ratio_participacion,obra_ratio_contrato_participacion
count,324,324.000000,324.000000,324.0,324.0,324.0,324.000000,324.000000
unique,324,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,2002060-2434-702592-2064311-19777,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,16.200617,7.447531,1.0,1.0,1.0,1.703704,0.324165
std,NaN,34.724923,8.969178,0.0,0.0,0.0,0.936953,0.373679
min,NaN,1.000000,1.000000,1.0,1.0,1.0,1.000000,0.003484
25%,NaN,3.000000,2.000000,1.0,1.0,1.0,1.000000,0.071429
50%,NaN,8.000000,5.000000,1.0,1.0,1.0,2.000000,0.125000
75%,NaN,14.000000,9.250000,1.0,1.0,1.0,2.000000,0.333333
max,NaN,287.000000,56.000000,1.0,1.0,1.0,7.000000,1.000000

##### PASO 3.3 — FEATURES MONETARIAS (o3c)

OBJETIVO. Construir:
* monto promedio
* desviación
* dispersión
* mínimo
* máximo

In [7]:
# ===============================
# PASO 3.3
# FEATURES MONETARIAS (o3c)
# ===============================

df_o3c = tablas_obra["o3c"].copy()

print("Shape original:", df_o3c.shape)

display(df_o3c.head())


# ===============================
# NORMALIZAR
# ===============================

df_o3c["IDENTIFICADOR_OBRA"] = (
    df_o3c["IDENTIFICADOR_OBRA"]
    .astype(str)
    .str.strip()
)

df_o3c["MONTO_OFERTADO"] = pd.to_numeric(
    df_o3c["MONTO_OFERTADO"],
    errors="coerce"
)


# ===============================
# FEATURES POR OBRA
# ===============================

feat_montos = (
    df_o3c
    .groupby("IDENTIFICADOR_OBRA")
    .agg(

        obra_monto_ofertado_mean=(
            "MONTO_OFERTADO",
            "mean"
        ),

        obra_monto_ofertado_std=(
            "MONTO_OFERTADO",
            "std"
        ),

        obra_monto_ofertado_min=(
            "MONTO_OFERTADO",
            "min"
        ),

        obra_monto_ofertado_max=(
            "MONTO_OFERTADO",
            "max"
        ),

        obra_n_ofertas=(
            "MONTO_OFERTADO",
            "count"
        ),

    )
    .reset_index()
)


# ===============================
# FEATURES DERIVADAS
# ===============================

feat_montos["obra_rango_ofertas"] = (
    feat_montos["obra_monto_ofertado_max"]
    -
    feat_montos["obra_monto_ofertado_min"]
)

feat_montos["obra_cv_ofertas"] = (
    feat_montos["obra_monto_ofertado_std"]
    /
    feat_montos["obra_monto_ofertado_mean"]
)


print("Shape features montos:", feat_montos.shape)

display(feat_montos.head())

display(
    feat_montos.describe(include="all")
)

Shape original: (5249, 8)

,NUMERO_CONTRATO,CODIGO_CONTRATO,IDENTIFICADOR_OBRA,NOMBRE_EMPRESA_GANADORA,RUC_GANADOR,RUC_PARTICIPANTE,NOMBRE_EMPRESA_PARTICIPANTE,MONTO_OFERTADO
0,"C.C. O, PARA LA SUPERVICION DE ELABORACION DE ...",2099542,2428356-2428356-767107-2099542-152016,DEXTRE MORIMOTO EDUARDO RAUL(*),10101999039,10101999039,DEXTRE MORIMOTO EDUARDO RAUL,653894.50
1,"C.C. O, PARA LA SUPERVICION DE ELABORACION DE ...",2099542,2428356-2428356-767107-2099542-152016,DEXTRE MORIMOTO EDUARDO RAUL(*),10101999039,10181420761,VELARDE SAGASTEGUI JUAN STALIN(*),653894.50
2,"C.C. O, PARA LA SUPERVICION DE ELABORACION DE ...",2099542,2428356-2428356-767107-2099542-152016,DEXTRE MORIMOTO EDUARDO RAUL(*),10101999039,20508114096,CAYSA ASOCIADOS S.A.C.,653894.50
3,"C.C. O, PARA LA SUPERVICION DE ELABORACION DE ...",2099542,2428356-2428356-767107-2099542-152016,DEXTRE MORIMOTO EDUARDO RAUL(*),10101999039,20600248333,CONSORCIO NORSUR,653894.50
4,001 - 2021,2077976,2234473-249557-729905-2077976-76727,CONSORCIO COMPANY,10277185534,10009549931,PADILLA PINEDO GUSTAVO,350687.72

Shape features montos: (324, 8)

,IDENTIFICADOR_OBRA,obra_monto_ofertado_mean,obra_monto_ofertado_std,obra_monto_ofertado_min,obra_monto_ofertado_max,obra_n_ofertas,obra_rango_ofertas,obra_cv_ofertas
0,2002060-2434-702592-2064311-19777,2.276555e+06,99700.654277,2235852.56,2480068.29,6,244215.73,0.043795
1,2002210-8880-869397-2169938-826,3.075133e+05,88509.140993,0.00,332000.00,14,332000.00,0.287822
2,2002210-8880-870112-2169901-826,2.845637e+05,2412.718344,283575.23,290000.00,13,6424.77,0.008479
3,2026767-16256-709096-2067605-143536,2.477358e+06,0.000000,2477357.77,2477357.77,20,0.00,0.000000
4,2027711-3876-682536-2050524-138320,3.073365e+06,97441.761873,3043955.25,3382172.49,23,338217.24,0.031705

,IDENTIFICADOR_OBRA,obra_monto_ofertado_mean,obra_monto_ofertado_std,obra_monto_ofertado_min,obra_monto_ofertado_max,obra_n_ofertas,obra_rango_ofertas,obra_cv_ofertas
count,324,3.240000e+02,2.520000e+02,3.240000e+02,3.240000e+02,324.000000,3.240000e+02,2.520000e+02
unique,324,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,2002060-2434-702592-2064311-19777,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,5.558995e+07,3.247720e+06,5.339879e+07,6.005079e+07,16.200617,6.651992e+06,1.055453e-01
std,NaN,1.700302e+08,2.453199e+07,1.659259e+08,1.962168e+08,34.724923,6.099679e+07,3.388117e-01
min,NaN,3.617408e+04,0.000000e+00,0.000000e+00,3.617408e+04,1.000000,0.000000e+00,0.000000e+00
25%,NaN,5.606390e+05,0.000000e+00,3.818661e+05,5.977418e+05,3.000000,0.000000e+00,0.000000e+00
50%,NaN,2.681625e+06,5.201301e-03,2.333714e+06,3.061990e+06,8.000000,0.000000e+00,2.139190e-08
75%,NaN,1.003246e+07,1.349359e+05,9.082065e+06,1.056024e+07,14.000000,1.095628e+05,4.986005e-02
max,NaN,1.792432e+09,3.396865e+08,1.792432e+09,2.191419e+09,287.000000,1.022284e+09,2.440970e+00

##### PASO 3.4 — FEATURES DE EJECUCIÓN (o5a)
Objetivo. Construir:
* promedios
* desviaciones
* flags
* indicadores ejecución

In [8]:
# ===============================
# PASO 3.4
# FEATURES EJECUCIÓN (o5a)
# ===============================

df_o5a = tablas_obra["o5a"].copy()

print("Shape original:", df_o5a.shape)

display(df_o5a.head())


# ===============================
# NORMALIZAR
# ===============================

df_o5a["IDENTIFICADOR_OBRA"] = (
    df_o5a["IDENTIFICADOR_OBRA"]
    .astype(str)
    .str.strip()
)

for col in ["PLANIFICADO", "REAL"]:

    df_o5a[col] = pd.to_numeric(
        df_o5a[col],
        errors="coerce"
    )


# ===============================
# FEATURES POR OBRA
# ===============================

feat_ejecucion = (
    df_o5a
    .groupby("IDENTIFICADOR_OBRA")
    .agg(

        obra_planificado_mean=(
            "PLANIFICADO",
            "mean"
        ),

        obra_real_mean=(
            "REAL",
            "mean"
        ),

        obra_planificado_max=(
            "PLANIFICADO",
            "max"
        ),

        obra_real_max=(
            "REAL",
            "max"
        ),

        obra_n_registros_ejecucion=(
            "REAL",
            "count"
        ),

        obra_n_anhos=(
            "ANHO",
            "nunique"
        ),

        obra_n_meses=(
            "MES",
            "nunique"
        ),

    )
    .reset_index()
)


# ===============================
# FEATURES DERIVADAS
# ===============================

feat_ejecucion["obra_ratio_real_plan"] = (
    feat_ejecucion["obra_real_mean"]
    /
    feat_ejecucion["obra_planificado_mean"]
)

feat_ejecucion["obra_desviacion_real_plan"] = (
    feat_ejecucion["obra_real_mean"]
    -
    feat_ejecucion["obra_planificado_mean"]
)


print("Shape features ejecución:", feat_ejecucion.shape)

display(feat_ejecucion.head())

display(
    feat_ejecucion.describe(include="all")
)

Shape original: (634, 15)

,CODIGO_UNICO,SECTOR,DEPARTAMENTO,NIVEL_GOBIERNO,IDENTIFICADOR_OBRA,ANHO,MES,PLANIFICADO,REAL,IND_INTERVENSION,IND_RESIDENTE,IND_MONTO_ADELANTO_MATERIALES,IND_MONTO_ADELANTO_DIRECTO,IND_FECHA_ADELANTO_MATERIALES,IND_FECHA_ADELANTO_DIRECTO
0,2331873,TRABAJO,MULTIDEPARTAMENTAL,GOBIERNO REGIONAL,2331873-371182-638870-2023471-102021,NaN,NaN,0.0,0.00,NORMAL,NORMAL,NORMAL,NORMAL,NORMAL,NORMAL
1,2331873,TRABAJO,MULTIDEPARTAMENTAL,GOBIERNO REGIONAL,2331873-371182-670830-2045952-102022,NaN,NaN,0.0,0.00,NORMAL,NORMAL,NORMAL,NORMAL,NORMAL,NORMAL
2,2233958,TRANSPORTE,MULTIDEPARTAMENTAL,GOBIERNO NACIONAL,2233958-4588-516149-2047423-102591,2023.0,3.0,1.0,0.76,NORMAL,NORMAL,NORMAL,NORMAL,NORMAL,NORMAL
3,2233958,TRANSPORTE,MULTIDEPARTAMENTAL,GOBIERNO NACIONAL,2233958-4588-516149-2047423-102591,2023.0,8.0,1.0,0.96,NORMAL,NORMAL,NORMAL,NORMAL,NORMAL,NORMAL
4,2233958,TRANSPORTE,MULTIDEPARTAMENTAL,GOBIERNO NACIONAL,2233958-4588-516149-2047423-102591,2023.0,6.0,1.0,0.96,NORMAL,NORMAL,NORMAL,NORMAL,NORMAL,NORMAL

Shape features ejecución: (326, 10)

,IDENTIFICADOR_OBRA,obra_planificado_mean,obra_real_mean,obra_planificado_max,obra_real_max,obra_n_registros_ejecucion,obra_n_anhos,obra_n_meses,obra_ratio_real_plan,obra_desviacion_real_plan
0,2002060-2434-702592-2064311-19777,0.0,0.0,0.0,0.0,1,0,0,NaN,0.0
1,2002210-8880-869397-2169938-826,0.0,0.0,0.0,0.0,1,0,0,NaN,0.0
2,2002210-8880-870112-2169901-826,0.0,0.0,0.0,0.0,1,0,0,NaN,0.0
3,2015918-1249-721938-2074791-45660,0.0,0.0,0.0,0.0,1,0,0,NaN,0.0
4,2026767-16256-709096-2067605-143536,0.0,0.0,0.0,0.0,1,0,0,NaN,0.0

,IDENTIFICADOR_OBRA,obra_planificado_mean,obra_real_mean,obra_planificado_max,obra_real_max,obra_n_registros_ejecucion,obra_n_anhos,obra_n_meses,obra_ratio_real_plan,obra_desviacion_real_plan
count,326,326.000000,326.000000,326.000000,326.000000,326.000000,326.000000,326.000000,70.000000,326.000000
unique,326,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,2002060-2434-702592-2064311-19777,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,0.126221,0.088592,0.148129,0.101595,1.944785,0.214724,1.144172,0.767329,-0.037629
std,NaN,0.289976,0.212481,0.321813,0.233449,2.080685,0.411262,2.406545,0.300425,0.115960
min,NaN,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.127389,-0.810000
25%,NaN,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.538971,0.000000
50%,NaN,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.797541,0.000000
75%,NaN,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.959675,0.000000
max,NaN,1.000000,0.968333,1.000000,0.990000,9.000000,1.000000,8.000000,1.617647,0.070000

##### Nuevas features.
Debido a valores extraños:
* Existen muchos planificados=0
* Solo 70 Obras tienen ratio valido.
* Existen obras en donde Real > Planificado (valorizaciones o sobreavance, o mala programación , o adelantos no programados)

##### Nota
Los valores nulos derivados de divisiones por cero no fueron eliminados automáticamente, debido a que representan posibles estados relevantes de las obras (sin ejecución, paralizadas o sin programación registrada).
Por lo que, se generaron variables indicadoras binarias para preservar dicha información como señal potencial de riesgo.

In [9]:
feat_ejecucion["obra_planificado_cero"] = (
    feat_ejecucion["obra_planificado_mean"] == 0
).astype(int)

feat_ejecucion["obra_real_cero"] = (
    feat_ejecucion["obra_real_mean"] == 0
).astype(int)

feat_ejecucion["obra_sin_ejecucion"] = (
    (
        feat_ejecucion["obra_planificado_mean"] == 0
    )
    &
    (
        feat_ejecucion["obra_real_mean"] == 0
    )
).astype(int)

##### PASO 4 — DEFINICIÓN DEL TARGET DE OBRA

##### Verificamos si existe Target, en los Datasets previos

In [10]:
df_o4b = tablas_obra["o4b"].copy()

display(
    df_o4b[
        [
            "RIESGO_OBRA",
            "RIESGO_DESCRIPCION_OBRA"
        ]
    ].drop_duplicates()
)

    RIESGO_OBRA  RIESGO_DESCRIPCION_OBRA
0             4  Extremadamente Riesgosa
1             2    Medianamente Riesgosa
20            3       Altamente Riesgosa
28            1       Bajamente Riesgosa
51            0               Sin Riesgo

##### PASO 5 — CONSTRUIR DATASET_OBRA_V4_MODEL

El modelo no utiliza identificadores personales ni empresariales como variables predictoras.
Los identificadores fueron usados únicamente para integración y consolidación de features.

##### BASE TARGET

In [11]:
# ============================================================
# BASE TARGET OBRA
# ============================================================

base_obra = (
    tablas_obra["o4b"][
        [
            "IDENTIFICADOR_OBRA",
            "RIESGO_OBRA",
            "RIESGO_DESCRIPCION_OBRA"
        ]
    ]
    .drop_duplicates()
    .copy()
)

print("Shape base_obra:", base_obra.shape)

display(base_obra.head())

Shape base_obra: (326, 3)

                    IDENTIFICADOR_OBRA  RIESGO_OBRA  RIESGO_DESCRIPCION_OBRA
0    2002060-2434-702592-2064311-19777            4  Extremadamente Riesgosa
1      2002210-8880-869397-2169938-826            2    Medianamente Riesgosa
2      2002210-8880-870112-2169901-826            2    Medianamente Riesgosa
3    2015918-1249-721938-2074791-45660            4  Extremadamente Riesgosa
4  2026767-16256-709096-2067605-143536            4  Extremadamente Riesgosa

##### VALIDAR DUPLICADOS TARGET

In [12]:
# ============================================================
# VALIDAR DUPLICADOS TARGET
# ============================================================

dup_target = (
    base_obra
    .groupby("IDENTIFICADOR_OBRA")
    .size()
    .reset_index(name="conteo")
)

dup_target = dup_target[dup_target["conteo"] > 1]

print("Obras con múltiples targets:", len(dup_target))

display(dup_target.head())

Obras con múltiples targets: 0

Empty DataFrame
Columns: [IDENTIFICADOR_OBRA, conteo]
Index: []

##### MERGE FEATURES

In [13]:
# ============================================================
# MERGE FEATURES
# ============================================================

dataset_obra_model = base_obra.copy()

# ------------------------------------------------------------
# comité
# ------------------------------------------------------------

dataset_obra_model = dataset_obra_model.merge(
    feat_comite,
    on="IDENTIFICADOR_OBRA",
    how="left"
)

# ------------------------------------------------------------
# participantes
# ------------------------------------------------------------

dataset_obra_model = dataset_obra_model.merge(
    feat_participantes,
    on="IDENTIFICADOR_OBRA",
    how="left"
)

# ------------------------------------------------------------
# montos
# ------------------------------------------------------------

dataset_obra_model = dataset_obra_model.merge(
    feat_montos,
    on="IDENTIFICADOR_OBRA",
    how="left"
)

# ------------------------------------------------------------
# ejecución
# ------------------------------------------------------------

dataset_obra_model = dataset_obra_model.merge(
    feat_ejecucion,
    on="IDENTIFICADOR_OBRA",
    how="left"
)

print("Shape dataset_obra_model:", dataset_obra_model.shape)

display(dataset_obra_model.head())

Shape dataset_obra_model: (326, 34)

,IDENTIFICADOR_OBRA,RIESGO_OBRA,RIESGO_DESCRIPCION_OBRA,obra_n_miembros_comite,obra_n_dnis_comite_unicos,obra_n_convocatorias_comite,obra_n_procesos_comite,obra_ratio_repeticion_comite,obra_n_participaciones,obra_n_rucs_participantes,...,obra_planificado_max,obra_real_max,obra_n_registros_ejecucion,obra_n_anhos,obra_n_meses,obra_ratio_real_plan,obra_desviacion_real_plan,obra_planificado_cero,obra_real_cero,obra_sin_ejecucion
0,2002060-2434-702592-2064311-19777,4,Extremadamente Riesgosa,6.0,6.0,1.0,1.0,1.0,6.0,6.0,...,0.0,0.0,1,0,0,NaN,0.0,1,1,1
1,2002210-8880-869397-2169938-826,2,Medianamente Riesgosa,6.0,6.0,1.0,1.0,1.0,14.0,14.0,...,0.0,0.0,1,0,0,NaN,0.0,1,1,1
2,2002210-8880-870112-2169901-826,2,Medianamente Riesgosa,6.0,6.0,1.0,1.0,1.0,13.0,13.0,...,0.0,0.0,1,0,0,NaN,0.0,1,1,1
3,2015918-1249-721938-2074791-45660,4,Extremadamente Riesgosa,6.0,6.0,1.0,1.0,1.0,NaN,NaN,...,0.0,0.0,1,0,0,NaN,0.0,1,1,1
4,2026767-16256-709096-2067605-143536,4,Extremadamente Riesgosa,6.0,6.0,1.0,1.0,1.0,20.0,10.0,...,0.0,0.0,1,0,0,NaN,0.0,1,1,1

##### VALIDAR COLUMNAS

In [14]:
# ============================================================
# VALIDACIÓN DE COLUMNAS PROHIBIDAS
# ============================================================

columnas_prohibidas = [
    "CODIGO_DNI",
    "DNI",
    "RUC",
    "CODIGO_RUC",
    "NOMBRE",
    "NOMBRE_EMPRESA",
    "NOMBRE_OBRA",
    "RAZON_SOCIAL"
]

bad_cols = []

for col in dataset_obra_model.columns:

    col_upper = col.upper()

    for bad in columnas_prohibidas:

        if bad in col_upper:
            bad_cols.append(col)

print("Columnas sospechosas:")
print(bad_cols)

Columnas sospechosas:
['obra_n_dnis_comite_unicos', 'obra_n_rucs_participantes']

##### VALIDAR UNA FILA POR OBRA

In [15]:
# ============================================================
# VALIDAR UNA FILA POR OBRA
# ============================================================

dup_final = (
    dataset_obra_model
    .groupby("IDENTIFICADOR_OBRA")
    .size()
    .reset_index(name="conteo")
)

dup_final = dup_final[dup_final["conteo"] > 1]

print("Obras duplicadas:", len(dup_final))

Obras duplicadas: 0

##### TARGET FINAL

In [16]:
# ============================================================
# TARGET FINAL
# ============================================================

dataset_obra_model = dataset_obra_model.rename(
    columns={
        "RIESGO_OBRA": "y_riesgo_obra_5niveles"
    }
)

print(
    dataset_obra_model["y_riesgo_obra_5niveles"]
    .value_counts()
    .sort_index()
)

y_riesgo_obra_5niveles
0     32
1     52
2     87
3      7
4    148
Name: count, dtype: int64

##### EXPORTAR

In [24]:
dataset_obra_model = dataset_obra_model.drop(
    columns=["RIESGO_DESCRIPCION_OBRA"]
)

In [25]:
# ============================================================
# EXPORTAR DATASET FINAL
# ============================================================
DATA_PROC = BASE / "data" / "processed"
output_path = DATA_PROC / "dataset_obra_v4_model.parquet"

dataset_obra_model.to_parquet(
    output_path,
    index=False
)

print("Dataset exportado:")
print(output_path)

print("\nShape final:")
print(dataset_obra_model.shape)

Dataset exportado:
C:\IA_Investigacion\Deteccion_Corrupcion\data\processed\dataset_obra_v4_model.parquet

Shape final:
(326, 33)

In [26]:
# ============================================================
# VALIDACIÓN FINAL DATASET_OBRA_V4_MODEL
# ============================================================

print("=" * 80)
print("SHAPE FINAL")
print("=" * 80)

print(dataset_obra_model.shape)

# ============================================================

print("\n" + "=" * 80)
print("COLUMNAS FINALES")
print("=" * 80)

for i, col in enumerate(dataset_obra_model.columns, 1):
    print(f"{i:02d}. {col}")

# ============================================================

print("\n" + "=" * 80)
print("DISTRIBUCIÓN TARGET")
print("=" * 80)

target_dist = (
    dataset_obra_model["y_riesgo_obra_5niveles"]
    .value_counts()
    .sort_index()
)

print(target_dist)

# ============================================================

print("\n" + "=" * 80)
print("PORCENTAJE TARGET")
print("=" * 80)

target_pct = (
    dataset_obra_model["y_riesgo_obra_5niveles"]
    .value_counts(normalize=True)
    .sort_index()
    * 100
)

print(target_pct.round(2))

# ============================================================

print("\n" + "=" * 80)
print("COLUMNAS SOSPECHOSAS")
print("=" * 80)

columnas_prohibidas = [
    "DNI",
    "RUC",
    "NOMBRE",
    "RAZON_SOCIAL",
    "CODIGO_DNI",
    "CODIGO_RUC"
]

bad_cols = []

for col in dataset_obra_model.columns:

    col_upper = col.upper()

    for bad in columnas_prohibidas:

        if bad in col_upper:
            bad_cols.append(col)

if len(bad_cols) == 0:
    print("✅ No se detectaron columnas prohibidas")
else:
    print("⚠️ Columnas sospechosas detectadas:")
    for c in bad_cols:
        print("-", c)

# ============================================================

print("\n" + "=" * 80)
print("TIPOS DE DATOS")
print("=" * 80)

display(
    dataset_obra_model.dtypes
    .reset_index()
    .rename(columns={
        "index": "columna",
        0: "dtype"
    })
)

# ============================================================

print("\n" + "=" * 80)
print("PRIMERAS FILAS")
print("=" * 80)

display(dataset_obra_model.head())

================================================================================
SHAPE FINAL
================================================================================
(326, 33)

================================================================================
COLUMNAS FINALES
================================================================================
01. IDENTIFICADOR_OBRA
02. y_riesgo_obra_5niveles
03. obra_n_miembros_comite
04. obra_n_dnis_comite_unicos
05. obra_n_convocatorias_comite
06. obra_n_procesos_comite
07. obra_ratio_repeticion_comite
08. obra_n_participaciones
09. obra_n_rucs_participantes
10. obra_n_contratos
11. obra_n_codigos_obra
12. obra_n_procesos
13. obra_ratio_participacion
14. obra_ratio_contrato_participacion
15. obra_monto_ofertado_mean
16. obra_monto_ofertado_std
17. obra_monto_ofertado_min
18. obra_monto_ofertado_max
19. obra_n_ofertas
20. obra_rango_ofertas
21. obra_cv_ofertas
22. obra_planificado_mean
23. obra_real_mean
24. obra_planificado_max
25. obra_real_max
26. obra_n_registros_ejecucion
27. obra_n_anhos
28. obra_n_meses
29. obra_ratio_real_plan
30. obra_desviacion_real_plan
31. obra_planificado_cero
32. obra_real_cero
33. obra_sin_ejecucion

================================================================================
DISTRIBUCIÓN TARGET
================================================================================
y_riesgo_obra_5niveles
0     32
1     52
2     87
3      7
4    148
Name: count, dtype: int64

================================================================================
PORCENTAJE TARGET
================================================================================
y_riesgo_obra_5niveles
0     9.82
1    15.95
2    26.69
3     2.15
4    45.40
Name: proportion, dtype: float64

================================================================================
COLUMNAS SOSPECHOSAS
================================================================================
⚠️ Columnas sospechosas detectadas:
- obra_n_dnis_comite_unicos
- obra_n_rucs_participantes

================================================================================
TIPOS DE DATOS
================================================================================

                              columna    dtype
0                  IDENTIFICADOR_OBRA   object
1              y_riesgo_obra_5niveles    int64
2              obra_n_miembros_comite  float64
3           obra_n_dnis_comite_unicos  float64
4         obra_n_convocatorias_comite  float64
5              obra_n_procesos_comite  float64
6        obra_ratio_repeticion_comite  float64
7              obra_n_participaciones  float64
8           obra_n_rucs_participantes  float64
9                    obra_n_contratos  float64
10                obra_n_codigos_obra  float64
11                    obra_n_procesos  float64
12           obra_ratio_participacion  float64
13  obra_ratio_contrato_participacion  float64
14           obra_monto_ofertado_mean  float64
15            obra_monto_ofertado_std  float64
16            obra_monto_ofertado_min  float64
17            obra_monto_ofertado_max  float64
18                     obra_n_ofertas  float64
19                 obra_rango_ofertas  float64
20                    obra_cv_ofertas  float64
21              obra_planificado_mean  float64
22                     obra_real_mean  float64
23               obra_planificado_max  float64
24                      obra_real_max  float64
25         obra_n_registros_ejecucion    int64
26                       obra_n_anhos    int64
27                       obra_n_meses    int64
28               obra_ratio_real_plan  float64
29          obra_desviacion_real_plan  float64
30              obra_planificado_cero    int64
31                     obra_real_cero    int64
32                 obra_sin_ejecucion    int64

================================================================================
PRIMERAS FILAS
================================================================================

,IDENTIFICADOR_OBRA,y_riesgo_obra_5niveles,obra_n_miembros_comite,obra_n_dnis_comite_unicos,obra_n_convocatorias_comite,obra_n_procesos_comite,obra_ratio_repeticion_comite,obra_n_participaciones,obra_n_rucs_participantes,obra_n_contratos,...,obra_planificado_max,obra_real_max,obra_n_registros_ejecucion,obra_n_anhos,obra_n_meses,obra_ratio_real_plan,obra_desviacion_real_plan,obra_planificado_cero,obra_real_cero,obra_sin_ejecucion
0,2002060-2434-702592-2064311-19777,4,6.0,6.0,1.0,1.0,1.0,6.0,6.0,1.0,...,0.0,0.0,1,0,0,NaN,0.0,1,1,1
1,2002210-8880-869397-2169938-826,2,6.0,6.0,1.0,1.0,1.0,14.0,14.0,1.0,...,0.0,0.0,1,0,0,NaN,0.0,1,1,1
2,2002210-8880-870112-2169901-826,2,6.0,6.0,1.0,1.0,1.0,13.0,13.0,1.0,...,0.0,0.0,1,0,0,NaN,0.0,1,1,1
3,2015918-1249-721938-2074791-45660,4,6.0,6.0,1.0,1.0,1.0,NaN,NaN,NaN,...,0.0,0.0,1,0,0,NaN,0.0,1,1,1
4,2026767-16256-709096-2067605-143536,4,6.0,6.0,1.0,1.0,1.0,20.0,10.0,1.0,...,0.0,0.0,1,0,0,NaN,0.0,1,1,1

### ANÁLISIS TÉCNICO DE FEATURES

### 1. features de Comite:
* obra_n_miembros_comite
* obra_ratio_repeticion_comite

Que obtenemos:
* Repetición de comite : Posible colusión
* Pocos DNIs únicos : concentración
* pocos procesos: baja competencia

### 2. features de Participantes:
* obra_n_participaciones
* obra_n_rucs_participantes
* obra_ratio_participacion

Que obtenemos:
* pocos participantes : Direccionamiento
* alta repetición : concentración
* pocos contratos: baja competencia

### 3. features de Montos:
* obra_cv_ofertas
* obra_rango_ofertas

Que obtenemos:
* CV bajo : Posible concertación
* rango muy pequeño : posible coordinación
* desviaciones enormes: outliers

### 4. features de Ejecución:
* obra_ratio_real_plan
* obra_desviacion_real_plan
* obra_sin_ejecucion

Que obtenemos:
* retraso : riesgo operativo
* desviación : mala planificación
* sin ejecución: posible paralización
* real > plan : anomalía